# src/alert.py

import os
import smtplib
from src.geoip import get_ip_details
from email.message import EmailMessage
from datetime import datetime
from dotenv import load_dotenv

# Load environment variables from .env
load_dotenv()

SENDER_EMAIL = os.getenv("SENDER_EMAIL")
APP_PASSWORD = os.getenv("APP_PASSWORD")
RECEIVER_EMAIL = os.getenv("RECEIVER_EMAIL")


def format_alert_email(ip, attempts, enrich=None, classification=None, threshold=None):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = []
    lines.append("🚨 SECURITY ALERT – IMMEDIATE ATTENTION REQUIRED\n")
    lines.append("A potential brute-force login attack has been detected.\n")

    lines.append("=== Incident Summary ===")
    lines.append("Attack Type: Brute-Force Login Attempt")
    lines.append("Severity: High")
    lines.append(f"Detection Time: {timestamp}\n")

    lines.append("=== Attacker Details ===")
    lines.append(f"IP Address: {ip}")

    if enrich and enrich.get("status") == "success":
        lines.append(f"Country: {enrich.get('country')}")
        lines.append(f"Region / City: {enrich.get('region')}, {enrich.get('city')}")
        lines.append(f"ISP / Organization: {enrich.get('isp')}")
        lines.append(f"Network (ASN): {enrich.get('asn')}")
        lines.append(f"Proxy / VPN Detected: {enrich.get('proxy')}")
        lines.append(f"Cloud / Hosting Provider: {enrich.get('hosting')}")
    else:
        lines.append("IP Intelligence: Unavailable")

    lines.append("\n=== Attack Behavior ===")
    lines.append(f"Failed Login Attempts: {attempts}")
    lines.append(f"Attack Classification: {classification}")
    lines.append(f"Detection Threshold: {threshold}\n")

    lines.append("=== Recommended Actions ===")
    lines.append("- Review authentication logs immediately")
    lines.append("- Block the IP address if malicious")
    lines.append("- Enforce strong passwords or MFA")
    lines.append("- Monitor for further suspicious activity\n")

    lines.append("This alert was generated automatically by Cyber Log Analyzer.")
    lines.append("— Security Monitoring System")

    return "\n".join(lines)


def send_email_alert(ip, attempts):
    geo = get_ip_details(ip)

    msg = EmailMessage()
    msg["Subject"] = "🚨 Security Alert: Brute-Force Attack Detected"
    msg["From"] = SENDER_EMAIL
    msg["To"] = RECEIVER_EMAIL

    body = f"""
SECURITY ALERT 🚨

A brute-force login attack has been detected.

IP Address: {ip}
Failed Attempts: {attempts}
"""

    if geo:
        body += f"""
Location Details:
Country: {geo['country']}
Region: {geo['region']}
City: {geo['city']}
ISP: {geo['isp']}
Organization: {geo['org']}
ASN: {geo['asn']}
Hosting Provider: {geo['hosting']}
Proxy/VPN: {geo['proxy']}
"""

    body += """
Recommended Actions:
- Block this IP if malicious
- Review authentication logs
- Enable MFA
- Monitor system closely

Generated by Cyber Log Analyzer
"""

    msg.set_content(body)

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(SENDER_EMAIL, APP_PASSWORD)
            server.send_message(msg)
        print("📧 Email alert sent successfully!")
    except Exception as e:
        print("❌ Email sending failed:", e)
